version: '3.9'

services:
  msds-engine:
    volumes:
      - ./msds-engine:/app
  api-gateway:
    volumes:
      - ./services/api-gateway:/app
  auth-service:
    volumes:
      - ./services/auth-service:/app
  user-service:
    volumes:
      - ./services/user-service:/app
  payment-service:
    volumes:
      - ./services/payment-service:/app